### ISSUE TITLE
Don't mention undocumented instructions in readme

### ISSUE THREAD

**Issue by casey** [omaskery/shenzhen.io-assembler#1]
I think that the fact that there are undocumented instructions is itself a spoiler, so I would just say that the source code contains spoilers.

**Comment by omaskery** [comment]
Hi, thanks for the comment! I've hopefully changed it to be less spoiler-y! :) If you agree I'll close the issue!

**Comment by casey** [comment]
Perfect! This is pretty cool, by the way :)

**Comment by omaskery** [comment]
Thanks :D! Have a nice day/evening ^_^
