### ISSUE TITLE
Feature require : Generate GTKView compatible outputs

### ISSUE THREAD

**Issue by ithinuel** [omaskery/shenzhen.io-assembler#2]
This would be so fancy to use the same tools as we do when looking at FPGA logs 😛

**Comment by omaskery** [comment]
Hi!

Thanks for opening an issue! Can you explain what you mean?

I've used GtkView for FPGA logs before, but am not sure what output an assembler should generate for viewing in GtkView!

Perhaps you mean if this program also emulated the processor it could record the output pin states?

**Comment by ithinuel** [comment]
Yes exactly !
It could be funny to see the output port's signal as we do in game when we push to analog pX or digital xY ports !
pX value would be maintain until it changes while xY would only be available for clock 1 tick.

**Comment by omaskery** [comment]
Whilst it's a neat idea, I don't want to make my assembler also an emulator. If I ever do implement an emulator, I'd do it as a separate application - at which point I will try and implement your suggestion! 😄
